#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_gateway/LICENSE 
#

##############################################################################
# Imports
##############################################################################

import sys
import argparse
import re
import roslib 
roslib.load_manifest('rocon_gateway')
import rospy
import rocon_gateway
import gateway_msgs
import rocon_gateway.console as console
import rocon_gateway.utils as utils

class Flags(object):
    flip = 'flip'
    unflip = 'unflip'
    
##############################################################################
# Logging
##############################################################################

class Logger(object):
    def __init(self):
        self.debug_flag = False
        
    def debug(self,msg):
        if self.debug_flag:
            console.pretty_print("%s\n"%msg, console.green)
    
    def green(self,msg):
        console.pretty_print("%s\n"%msg, console.green)
    
    def warning(self,msg):
        console.pretty_print("%s\n"%msg, console.yellow)
    
    def error(self,msg):
        console.pretty_print("%s\n"%msg, console.red)

logger = Logger()

##############################################################################
# Functions
##############################################################################
    
def parse_arguments():
    parser = argparse.ArgumentParser(description='Flip a local connection to a remote gateway')
    parser.add_argument('-d', '--debug', action='store_true', help='print debugging information')
    args = parser.parse_args()
    logger.debug_flag = args.debug
    return args

def resolve_local_gateway():
    master = rocon_gateway.LocalMaster()
    gateway_namespace = master.findGatewayNamespace()
    if not gateway_namespace:
        logger.error("Could not find a local gateway - did you start it?")
        raise rocon_gateway.GatewayError("Cannot proceed without a local gateway, aborting")
    logger.debug("Found a local gateway at %s"%gateway_namespace)
    return gateway_namespace

   
def resolve_remote_gateways(gateway_namespace):
    '''
      @raise rocon_gateway.GatewayError: if no remote gateways or no matching gateways available. 
    '''
    remote_gateways = []
    remote_gateway_info = rospy.ServiceProxy(gateway_namespace+'/remote_gateway_info', gateway_msgs.srv.RemoteGatewayInfo)
    req = gateway_msgs.srv.RemoteGatewayInfoRequest()
    req.gateways = []
    resp = remote_gateway_info(req)
    if len(resp.gateways) == 0:
        raise rocon_gateway.GatewayError("No remote gateways to flip/unflip to, aborting.")
    index = 0;
    max_index = len(resp.gateways) - 1
    if max_index == 0:
        logger.debug("Automatically selecting target gateway %s (only one visible)"%resp.gateways[0].name)
        remote_gateways.append(resp.gateways[0].name)
    else:
        print("Select a target gateway:")
        for remote_gateway in resp.gateways:
            print("    " + str(index) + ") " + remote_gateway.name)
            index +=1
        input_response = raw_input("Enter [0-%s] or regex [e.g. pir.* or .*]: "%str(max_index))
        try:
            index = int(input_response)
            remote_gateways.append(resp.gateways[index].name)
        except ValueError, e: # It's a regex
            for remote_gateway in resp.gateways:
                if re.match(input_response, remote_gateway.name):
                    remote_gateways.append(remote_gateway.name)
    return remote_gateways

def resolve_flags():
    '''
      Currently only flip/unflip flag
    '''
    response = raw_input("> Flip or unflip connections (f/u): ")
    while response != 'f' and response != 'u':
        response = raw_input("> Valid options are (f/u): ")
    if response == 'f':
        return Flags.flip
    else:
        return Flags.unflip 

def resolve_flipped_interface(gateway_namespace):
    gateway_info = rospy.ServiceProxy(gateway_namespace+'/gateway_info', gateway_msgs.srv.GatewayInfo)
    req = gateway_msgs.srv.GatewayInfoRequest()
    resp = gateway_info(req)
    if len(resp.flipped_connections) == 0:
        raise rocon_gateway.GatewayError("No flipped connections to unflip, aborting.")
    index = 0;
    max_index = len(resp.flipped_connections) - 1
    unflips = []
    if max_index == 0:
        logger.debug("Automatically selecting %s (only one visible)"%resp.flipped_connections.rule.name)
        unflips.append(resp.flipped_connections.rule)
    else:
        print("Select a connection to unflip (gateway-name-type-node):")
        for connection in resp.flipped_connections:
            print("    " + str(index) + ") "),
            console.pretty_print(connection.gateway,console.red)
            print("-"),
            console.pretty_print(connection.rule.name,console.green)
            print("-"),
            console.pretty_print(connection.rule.type,console.cyan)
            print("-"),
            console.pretty_print(connection.rule.node+"\n",console.yellow)
            index +=1
        input_response = raw_input("Enter [0-%s] or regex keyed by name [e.g. /cha.* or .*]: "%str(max_index))
        try:
            index = int(input_response)
            unflips.append(resp.flipped_connections[index])
        except ValueError, e: # It's a regex
            for connection in resp.flipped_connections:
                if re.match(input_response, connection.rule.name):
                     unflips.append(connection)
    return unflips

def resolve_connections(remote_gateways):
    master = rocon_gateway.LocalMaster()
    connection_dictionary = master.getConnectionState()
    connections = []
    for connection_type in connection_dictionary:
        connections.extend(connection_dictionary[connection_type])
    # TODO prune topics that are already flipped to target gateways here 
    # should never get zero connections in a ros system, don't check
    rules = []
    index = 0;
    max_index = len(connections) - 1
    flips = []
    print("Select a connection to flip (name-type-node):")
    for connection in connections:
        print("    " + str(index) + ") "),
        console.pretty_print(connection.rule.name,console.green)
        print("-"),
        console.pretty_print(connection.rule.type,console.cyan)
        print("-"),
        console.pretty_print(connection.rule.node+"\n",console.yellow)
        index +=1
    input_response = raw_input("Enter [0-%s] or regex keyed by name [e.g. /cha.* or .*]: "%str(max_index))
    try:
        index = int(input_response)
        for remote_gateway in remote_gateways:
            flips.append(gateway_msgs.msg.RemoteRule(remote_gateway,connections[index].rule))
    except ValueError, e: # It's a regex
        for connection in connections:
            if re.match(input_response, connection.rule.name):
                 for remote_gateway in remote_gateways:
                     flips.append(gateway_msgs.msg.RemoteRule(remote_gateway,connection.rule))
    return flips

def flip_rules(gateway_namespace, remote_rules, flag):
    print gateway_namespace
    flip_service = rospy.ServiceProxy(gateway_namespace+'/flip',gateway_msgs.srv.Remote)
    rospy.sleep(0.5)
    req = gateway_msgs.srv.RemoteRequest()
    for remote_rule in remote_rules:
        req.cancel = True if flag == Flags.unflip else False
        req.remotes.append(remote_rule)
        print req
        resp = flip_service(req)

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    
    rospy.init_node('flip')
    args = parse_arguments()
    gateway_namespace = None
    remote_gateways = None
    flag = None
    remote_rules = None
    
    try:
        gateway_namespace = resolve_local_gateway()
        flag = resolve_flags()
        if flag == Flags.unflip:
            remote_rules = resolve_flipped_interface(gateway_namespace)
        else:
            remote_gateways = resolve_remote_gateways(gateway_namespace)
            remote_rules = resolve_connections(remote_gateways)
    except rocon_gateway.GatewayError, e:
        logger.error(str(e))
        sys.exit(1)
    console.pretty_print("Flip Information\n",console.bold)
    print("  Local Gateway: %s"%gateway_namespace)
    print("  Operation    : %s"%flag)
    first_rule = True
    print("  Flip Rules   : "),
    for rule in remote_rules:
        if first_rule:
            first_rule = False
        else:
            print("               : "),
        console.pretty_print(rule.gateway,console.red)
        print("-"),
        console.pretty_print(rule.rule.name,console.green)
        print("-"),
        console.pretty_print(rule.rule.type,console.cyan)
        print("-"),
        console.pretty_print(rule.rule.node+"\n",console.yellow)
    proceed = raw_input("Proceed? (y/n): ")
    if proceed == 'y':
        flip_rules(gateway_namespace, remote_rules, flag)
    rospy.sleep(1)
