#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/license/LICENSE
#

##############################################################################
# Imports
##############################################################################

import sys
import argparse
import rospy
import rocon_gateway
import gateway_msgs.msg as gateway_msgs
import gateway_msgs.srv as gateway_srvs
import rocon_gateway_utils
import rocon_console.console as console
import rocon_python_comms

##############################################################################
# Functions
##############################################################################


def parse_arguments():
    parser = argparse.ArgumentParser(description='Prettifies remote gateway info')
    args = parser.parse_args()
    return args


def resolve_local_gateway():
    master = rocon_gateway.LocalMaster()
    gateway_namespace = master.find_gateway_namespace()
    if not gateway_namespace:
        console.error("Could not find a local gateway - did you start it?")
        raise rocon_gateway.GatewayError("Cannot proceed without a local gateway, aborting")
    #console.debug("Found a local gateway at %s"%gateway_namespace)
    gateway_info = rocon_python_comms.SubscriberProxy(gateway_namespace + '/gateway_info', gateway_msgs.GatewayInfo)()
    return gateway_namespace, gateway_info.ip


def resolve_remote_gateways(gateway_namespace):
    '''
      @raise rocon_gateway.GatewayError: if no remote gateways or no matching gateways available.
    '''
    remote_gateway_info = rospy.ServiceProxy(gateway_namespace + '/remote_gateway_info', gateway_srvs.RemoteGatewayInfo)
    req = gateway_srvs.RemoteGatewayInfoRequest()
    req.gateways = []
    resp = remote_gateway_info(req)
    #print("Remote gateway info: %s" % resp)
    return resp.gateways

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':

    rospy.init_node('pull')
    args = parse_arguments()
    gateway_namespace = None
    remote_gateways = None
    ip = None

    try:
        gateway_namespace, ip = resolve_local_gateway()
        remote_gateways = resolve_remote_gateways(gateway_namespace)
    except rocon_gateway.GatewayError, e:
        console.error(str(e))
        sys.exit(1)
    console.pretty_print("Local Gateway\n", console.bold)
    print("  Namespace: %s" % gateway_namespace)
    print("  Ip/Hostname: %s" % ip)
    # I wanted to put local ip here
    for gateway in remote_gateways:
        console.pretty_print("Remote Gateway\n", console.bold)
        print("  Name        : %s" % rocon_gateway_utils.gateway_basename(gateway.name))
        print("  Hash Name   : %s" % gateway.name)
        print("  Ip/Hostname : %s" % gateway.ip)
        print("  Firewall    : %s" % str(gateway.firewall).lower())
        print("  Alive       : "),
        if not gateway.conn_stats.gateway_available:
            console.pretty_print(str(gateway.conn_stats.gateway_available), console.red)
            print(" (last Seen %i seconds ago)" % gateway.conn_stats.time_since_last_seen)
        else:
            console.pretty_print(str(gateway.conn_stats.gateway_available) + "\n", console.green)
        if gateway.conn_stats.network_type == gateway_msgs.ConnectionStatistics.WIRED:
            print("  Connection  : wired")
        elif gateway.conn_stats.network_type == gateway_msgs.ConnectionStatistics.WIRELESS:
            print("  Connection  : wireless")
        else:
            print("  Connection  : unknown")
        print("  Latency from Hub(ms)")
        print("    Min/Max        : %.3f-%.3f" % (gateway.conn_stats.ping_latency_min,
                                                  gateway.conn_stats.ping_latency_max))
        print("    Average        : %.3f" % gateway.conn_stats.ping_latency_avg)
        print("    Mean Deviation : %.3f" % gateway.conn_stats.ping_latency_mdev)
        if gateway.conn_stats.network_type == gateway_msgs.RemoteGateway.WIRELESS:
            print("  Wireless statistics")
            print("    Bitrate   : %sMb/s" % (gateway.conn_stats.wireless_bitrate / 1000000))
            print("    Quality   : %s/70" % gateway.conn_stats.wireless_link_quality)
            print("    Signal Lvl: %sdBm" % int(gateway.conn_stats.wireless_signal_level))
        print("  Public Interface")
        if len(gateway.public_interface) == 0:
            print("          : -")
        for rule in gateway.public_interface:
            print("          : "),
            console.pretty_print(rule.name, console.green)
            print("-"),
            console.pretty_print(rule.type, console.cyan)
            print("-"),
            console.pretty_print(rule.node + "\n", console.yellow)

        print("  Flipped Interface")
        if len(gateway.flipped_interface) == 0:
            print("          : -")
        for remote_rule in gateway.flipped_interface:
            print("          : "),
            console.pretty_print(remote_rule.gateway, console.red)
            print("-"),
            console.pretty_print(remote_rule.rule.name, console.green)
            print("-"),
            console.pretty_print(remote_rule.rule.type, console.cyan)
            print("-"),
            console.pretty_print(remote_rule.rule.node + "\n", console.yellow)

        print("  Pulled Interface")
        if len(gateway.pulled_interface) == 0:
            print("          : -")
        for remote_rule in gateway.pulled_interface:
            print("          : "),
            console.pretty_print(remote_rule.gateway, console.red)
            print("-"),
            console.pretty_print(remote_rule.rule.name, console.green)
            print("-"),
            console.pretty_print(remote_rule.rule.type, console.cyan)
            print("-"),
            console.pretty_print(remote_rule.rule.node + "\n", console.yellow)
