# Default values are commented with a #.

## Uri for the hub - set this if you want to manually
## find the gateway hub instead of via zeroconf.
## Typical setting for a redis server on ubuntu would
## be: http://localhost:6379
# hub_uri: 

## Hub whitelist/blacklists - use these to control 
## which hubs you wish to work with.
## Hubs are referred to either by ip or hub name. 
# hub_whitelist: []
# hub_blacklist: []

## Gateway name - this is a human readable convenience only
# name: 'gateway'

## Watch loop period - how long the watcher should sleep
## inbetween checking if system state needs synchronisation
# watch_loop_period: 10

# Used to block/permit remote gateway's from flipping to this gateway.
# firewall: true

# Static rules
#default_advertisements: 
#    - name: /chatter
#      node: None
#      type: publisher
#    - name: /chat*
#      node: None
#      type: subscriber
#default_flips: how to do these? 
#    - gatewa{ name: /chatter
#      node: None
#      type: publisher
#    - name: /chat*
#      node: None
#      type: subscriber
