#!/bin/bash

port=$1
name=$2
args=$3

control_c() {
  exit
}

ROS_MASTER_URI=http://localhost:$port; rosservice call --wait $name $args
while [ $? <> 0 ]
do
  trap control_c SIGINT
  sleep 1
  ROS_MASTER_URI=http://localhost:$port; rosservice call --wait $name $args
done

