#!/usr/bin/env python
#       
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_multimaster/master/rocon_gateway/LICENSE 
#

##############################################################################
# Imports
##############################################################################

import rocon_utilities

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rocon_utilities.launch()